depth:
  type: None
pose:
  trans_scale: 1.0
  learn_pose: True
  layers_feat: [null,256,256,256,256,256,256,256,256] 
  skip: [4]
  pose_lr_t: 5.e-5                                         # learning rate of camera poses
  lr_pose_end: 2.e-5                                      # terminal learning rate of camera poses (only used with sched_pose.type=ExponentialLR)
  pose_lr_r: 5.e-5                                          # learning rate of camera poses
  lr_rots_end: 2.e-6                                      # terminal learning rate of camera poses (only used with sched_pose.type=ExponentialLR)
  max_index: 30
  device: cuda:0
  memorize: False
dataloading:
  skip: 4
  path: /workspace/eth/datasets/Tanks
  scene: ['Ignatius']
  customized_focal: False
  random_ref: 1
training:
  out_dir:  out/Tanks/rebuttal/R_Ignatius_ours_skip4_quad4_mem_rerun1
  auto_scheduler: True
  regularize: True
  memorize: True
  memorize_start: 0

extract_images:
  resolution: [540, 960]