depth:
  type: None
pose:
  learn_pose: True
  layers_feat: [null,256,256,256,256,256,256,256,256] 
  skip: [4]
  pose_lr_t: 1.e-4                                         # learning rate of camera poses
  lr_pose_end: 2.e-5                                      # terminal learning rate of camera poses (only used with sched_pose.type=ExponentialLR)
  pose_lr_r: 5.e-5                                          # learning rate of camera poses
  lr_rots_end: 2.e-6                                      # terminal learning rate of camera poses (only used with sched_pose.type=ExponentialLR)
  max_index: 150
  device: cuda:0
  memorize: True
dataloading:
  path: /workspace/eth/datasets/Tanks
  scene: ['Ballroom']
  customized_focal: False
  random_ref: 1
training:
  out_dir: out/Tanks/Ballroom_ct_quad3_m_s_r_0
  auto_scheduler: True
  regularize: True
extract_images:
  resolution: [540, 960]
  model_file_pose: ''