depth:
  type: None
pose:
  learn_pose: True
dataloading:
  skip: 2
  path: /workspace/eth/datasets/Tanks
  scene: ['Ignatius']
  customized_focal: False
  random_ref: 1
training:
  out_dir:  out/Tanks/Ignatius_skip2_rerun_
  auto_scheduler: True
extract_images:
  resolution: [540, 960]