depth:
  type: None
pose:
  learn_pose: True
dataloading:
  skip: 2
  path: /workspace/eth/datasets/Tanks
  scene: ['Museum']
  customized_focal: False
  random_ref: 1
training:
  out_dir:  out/Tanks/Museum_skip2
  auto_scheduler: True
extract_images:
  resolution: [540, 960]