depth:
  type: None
pose:
  trans_scale: 1.5
  learn_pose: True
  layers_feat: [null,256,256,256,256,256,256,256,256] 
  skip: [4]
  pose_lr_t: 1.e-5                                       # learning rate of camera poses
  lr_pose_end: 2.e-5                                      # terminal learning rate of camera poses (only used with sched_pose.type=ExponentialLR)
  pose_lr_r: 5.e-5                                          # learning rate of camera poses
  lr_rots_end: 2.e-6                                      # terminal learning rate of camera poses (only used with sched_pose.type=ExponentialLR)
  max_index: 25
  device: cuda:0
  memorize: False
  # scheduler: True
dataloading:
  skip: 4
  path: /workspace/eth/datasets/Tanks
  scene: ['Museum']
  customized_focal: False
  random_ref: 1
training:
  out_dir:  out/Tanks/R_Museum_ct_ours_skip4_02
  auto_scheduler: True
  regularize: True
  # scheduling_start: 1000
extract_images:
  resolution: [540, 960]
