depth:
  type: None
pose:
  learn_pose: True
  layers_feat: [null,256,256,256,256,256,256,256,256] 
  skip: [4]
  posenc: 5
  pose_lr_t: 5.e-6                                          # learning rate of camera poses
  lr_pose_end: 5.e-7                                      # terminal learning rate of camera poses (only used with sched_pose.type=ExponentialLR)
  pose_lr_r: 1.e-6                                          # learning rate of camera poses
  lr_rots_end: 2.e-7                                      # terminal learning rate of camera poses (only used with sched_pose.type=ExponentialLR)
  max_index: 200
  device: cuda:0
dataloading:
  path: data/Tanks
  scene: ['Family']
  customized_focal: False
  random_ref: 1
  sample_rate: 2
training:
  out_dir:  out/Tanks/Family_ct_mem
  auto_scheduler: True
  scheduling_epoch: 5000
  regularize: True
extract_images:
  resolution: [540, 960]
  model_file_pose: [model_pose_rots.pt, model_pose_trans.pt]
  model_file_rots: model_pose_rots.pt
  model_file_trans: model_pose_trans.pt
  model_file_focal: model_focal.pt
eval_pose:
  type_to_eval: train