depth:
  type: None
pose:
  learn_pose: True
dataloading:
  path: /SSD1/qimaqi/Tanks
  scene: ['Ignatius']
  customized_focal: False
  random_ref: 1
  skip: 2
training:
  out_dir:  out/Tanks/Ignatius_skip2
  auto_scheduler: True
extract_images:
  resolution: [540, 960]