depth:
  type: None
pose:
  learn_pose: True
dataloading:
  path: /cluster/work/cvl/qimaqi/Tanks
  scene: ['Ignatius']
  customized_focal: False
  random_ref: 1
training:
  out_dir:  out/Tanks/Ignatius_debug
  auto_scheduler: True
extract_images:
  resolution: [540, 960]