depth:
  type: None
pose:
  learn_pose: True
  layers_feat: [null,256,256,256,256,256,256,256,256] 
  skip: [4]
  lr_pose: 1.e-3                                          # learning rate of camera poses
  lr_pose_end: 2.e-5                                      # terminal learning rate of camera poses (only used with sched_pose.type=ExponentialLR)
  lr_rots: 1.e-4                                          # learning rate of camera poses
  lr_rots_end: 2.e-6                                      # terminal learning rate of camera poses (only used with sched_pose.type=ExponentialLR)
  max_index: 120
dataloading:
  path: data/Tanks
  scene: ['Ignatius']
  customized_focal: False
  random_ref: 1
training:
  out_dir:  out/Tanks/Ignatius_ct
  auto_scheduler: True
extract_images:
  resolution: [540, 960]